---
title: "GALGOS Cadena en R"
output: html_notebook
---

INPUT: datasets preparados, 
OUTPUT: análisis, datasets elaborados y modelos

Analisis de datasets en proyecto GALGOS.

Importando datos desde MySQL:

```{r}
library(RMySQL)
#library(DBI)

#Conexiones ya abiertas
conexiones_abiertas <- dbListConnections(MySQL())
#Cerramos las conexiones abiertas
#dbDisconnect(dbListConnections(MySQL())[[1]])

mydb = dbConnect(MySQL(), user='root', password='datos1986', dbname='datos_desa', host='localhost')
on.exit(dbDisconnect(mydb))
#dbListTables(mydb)  #Todas las tablas que tengo

#Datasets INPUT
pasado_f_rs <- dbSendQuery(mydb, "SELECT * FROM datos_desa.tb_ds_pasado_train_features_TOTAL LIMIT 1000000")
pasado_f <- dbFetch(pasado_f_rs, n = -1)
dbClearResult(pasado_f_rs)

pasado_t_rs <- dbSendQuery(mydb, "SELECT * FROM datos_desa.tb_ds_pasado_train_targets_TOTAL LIMIT 1000000")
pasado_t <- dbFetch(pasado_t_rs, n = -1)
dbClearResult(pasado_t_rs)

#Sacar DATASETS para usarlos despues
attach(pasado_f)
attach(pasado_t)
```

## ANALISIS PRELIMINAR DE DATOS

```{r}
head(pasado_f)
boxplot(pasado_f, cex.axis=0.5) 

head(pasado_t)
boxplot(pasado_t, cex.axis=0.5) 
```
Vemos que hay variables con outliers y otras leptocúrticas (apretadas en torno a la media).
```{r}
#summary(pasado_f)
lapply(pasado_f, summary)
```





